SELECT FUND_INFO.L_FUND_ID,
       FUND_ASSET.L_TRADE_DATE,
       FUND_INFO.VC_FUND_NAME,
       FUND_INFO.VC_FUND_NAME_FULL,
       FUND_INFO.VC_FUND_CODE,
       FUND_INFO.VC_FUND_TYPE,
       FUND_ASSET.EN_FUND_VALUE,
       HDF.FOF_MKT,
       HDF.FOF_MKT / FUND_ASSET.EN_FUND_VALUE POSITION,
       CASE
           WHEN FUND_INFO.VC_FUND_TYPE LIKE '%¹«Ä¼%' THEN 'T+1'
           ELSE DECODE(FUND_INFO.VC_VALUE_AGING, NULL, NULL, 'T+' || FUND_INFO.VC_VALUE_AGING)
           END                       VALUE_TIME
FROM ZHFX.TFUNDINFO_TEST FUND_INFO
         LEFT JOIN ZHFX.TFUNDASSET FUND_ASSET ON FUND_INFO.L_FUND_ID = FUND_ASSET.L_FUND_ID
         LEFT JOIN (SELECT HDF.L_FUND_ID,
                           HDF.L_TRADE_DATE,
                           SUM(CASE WHEN FD.VC_INVEST_TYPE = '»õ±ÒÐÍ' THEN 0 ELSE HDF.EN_VALUE_MARKET END) FOF_MKT
                    FROM ZHFX.THOLDINGDETAILFUND HDF
                             LEFT JOIN ZHFX.TMUTUALFUNDDESCRIPTION FD ON HDF.VC_WIND_CODE = FD.VC_WIND_CODE
                    WHERE L_TRADE_DATE = 20221021
                    GROUP BY HDF.L_FUND_ID, HDF.L_TRADE_DATE) HDF
                   ON FUND_ASSET.L_FUND_ID = HDF.L_FUND_ID AND FUND_ASSET.L_TRADE_DATE = HDF.L_TRADE_DATE
WHERE FUND_ASSET.L_TRADE_DATE = 20221021
  AND (FUND_INFO.VC_FUND_NAME_FULL LIKE '%FOF%'
    OR FUND_INFO.VC_FUND_NAME_FULL NOT LIKE '%FOF%' AND FUND_ASSET.EN_FUND_ASSET / FUND_ASSET.EN_FUND_VALUE >= 0.5)
