-- 估值时效 （针对专户）
SELECT FUND_INFO.C_TAFUNDCODE, FUND_INFO.C_FUNDNAME, FIO.C_CONTENT VALUE_AGING
FROM PLMS2_TPDTFUNDINFO FUND_INFO
         LEFT JOIN PLMS2_TFUNDINFOVERTICAL FIO ON FUND_INFO.C_FUNDCODE = FIO.C_FUNDCODE
WHERE FIO.C_PROCODE = 'C_EVALUATEDONEDAYS'
  AND FUND_INFO.C_TAFUNDCODE IS NOT NULL